### ISSUE TITLE
What is nodeSize?

### ISSUE THREAD

**Issue by PaTiToMaSteR** [tsreaper/ai-plays-flappybird#3]
Hi there, I'm trying to learn about neural networks and your source code seems to be small enough and very effective to start with :)

I'm stuck trying to understand the configuration of your Network, exactly nodeSize, and how you use that value to generate the next generation. My understanding is very limited, but as far I know you should have:
- input nodes
-- Pipe distance
-- Pipe height
-- 2nd pipe height
- hidden nodes ¿?
- output node -> triggers flap or not

I'm not sure if you follow that structure, but I cannot understand what does nodeSize or edges.
Also, I'm completely lost atm to understand how you propagate the knowledge from one generation to another.

Thanks for the tips and share the code!

**Comment by tsreaper** [comment]
This project is a simple combination of the neural network and the genetic algorithm, so the network in this project isn't very "traditional". The structure of the network will change from generation to generation.

The network in an individual starts with a very simple structure containing only input nodes and an output node and no hidden nodes. When two individuals are selected to breed a new-born individual, their network structures are combined randomly to form the network structure of the new individual, therefore propagating the knowledge to the new generation. The new individual may also mutate, adding/deleting a hidden node or an edge in its network, or changing the weight of an edge. This process seems to be quite random, but this is exactly how the genetic algorithm works.

`nodeSize` in my code is the number of nodes in the network, including input nodes and hidden nodes, but excluding output node (as there is only one output node).

**Comment by PaTiToMaSteR** [comment]
Oh! thanks for the info. Great :)
